name: Deploy to VPS

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'bash -s' < ./deploy.sh
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
