groups: 
  - name: alert.rules
    rules: 
      - alert: HighCpuUsage
        expr: rate(process_cpu_second_total[1m]) > 0.5
        for: 1m 
        labels:
          saverity: critical
        annotatinons:
          summary: "CPU usage is high"
          description: "Process {{ $labels.instance }} consume a lot of CPU"
