groups: 
  - name: alert.rules
    rules: 
      - alert: HighCpuUsage
        expr: rate(process_cpu_second_total{instance="traefik:8080", job="docker"}[1m]) > 0.5 #monitoring for last minute alert if cpu > 0.5
        for: 1m 
        labels:
          saverity: critical
        annotatinons:
          summary: "CPU usage is high"
          description: "Process {{ $labels.instance }} consume a lot of CPU"



#This alert can be used to check if Telegram alert is working
#groups:
  #- name: alert.rules
    #rules:
      #- alert: AlwaysFiring
        #expr: vector(1)
        #for: 10s
        #labels:
          #severity: test
        #annotations:
          #summary: "Testing alert"
          #description: "This alert always works, just to check delivery in Telegram"
