api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443" 
    
metrics: 
  prometheus:
    addEntryPointsLabels: true 
    addRoutersLabels: true 
    addServicesLabels: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "your-email@example.com"
      storage: acme.json
      httpChallenge:
        entryPoint: web

